name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
 
        
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install && yarn dev

  zap_scan:
    runs-on: ubuntu-latest
    permissions: write-all
    name: zap
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'http:localhost:5000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'